### ISSUE TITLE
[FEATURE] - Expand session functionality to include which programming language is allowed.

### ISSUE THREAD

**Issue by JMyrtue** [p7-projekt/api-backend#119]
### Summary

With the addition of a new language, an instructor should be allowed to determine which specific languages are allowed for a specific session.

Entails:
- new database table AllowedLanguageInSession with reference to a session and a language enum. 
  - many-to-many relation.
- Update API to support language specification of a session.

### Definition of Done

When session is modified throughout the backend, the support language specification.

**Comment by KristianS93** [comment]
Fixed in #106
