### ISSUE TITLE
Instructor created exercises

### ISSUE THREAD

**Issue by JMyrtue** [p7-projekt/api-backend#15]
An instructor should be able to create new exercises.

Entails:
- Validating that all required data is received from the frontend.
- Restructuring the received data to a format acceptable to k3s/haskell-docker.
- Sending the data to k3s and receiving a response.
- Storing the new testcase in the database or inform the frontend of failed compilation/test cases.

**Comment by KristianS93** [comment]
https://www.learndapper.com/saving-data/insert#dapper-insert-multiple-rows
