### ISSUE TITLE
Instructor created sessions

### ISSUE THREAD

**Issue by JMyrtue** [p7-projekt/api-backend#19]
### Summary

Instructors must be able to create a session with exercises associated.

Entails:
- Validating request from client-side.
- Creating session instance in database.
- (Maybe) generating a join code for students, and serve it to the frontend.

### Basic Example

.

### Drawbacks

.

### Unresolved questions

Exercises must be pre-served to the client, such that they can sent with the session-creation request.

**Comment by KristianS93** [comment]
Rest naming conventions: https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/#h-name-collections-with-plural-nouns

**Comment by KristianS93** [comment]
@39 when doing the authentication of especially anonymous users should be related to the students tables, however it should be renamed to participants. Maybe even anonymous participants, as this should be the only purpose of the table.

**Comment by KristianS93** [comment]
We should consider how it should work with joining a session, right now the anonymous user role doesnt really get used in the temporary student table. Should the role anonymous user exist outside of the run time ?
