### ISSUE TITLE
[FEATURE] - Anonymous users can join sessions

### ISSUE THREAD

**Issue by JMyrtue** [p7-projekt/api-backend#24]
### Summary

Anonymous users of the system must be able to join sessions created by Instructors.

Entails creating anonymous users, and binding them to a session in the database.

### Unresolved questions

Currently, the `student` in [this file](https://github.com/p7-projekt/api-backend/blob/master/schema.sql), does not entail any delete on cascade - Is this an oversight?

### Definition of Done

When a new `student` is created in the database, with referral to the correct `session` .

**Comment by KristianS93** [comment]
Solved in #19
