### ISSUE TITLE
[FEATURE] - Exercise endpoints

### ISSUE THREAD

**Issue by JMyrtue** [p7-projekt/api-backend#53]
### Reference Issues

#15 

### Summary

Create additional endpoints for exercises.

Should be possible to: 
- `GET \` - get all exercises of an instructor.
- `GET\id\` - get a specific exercises based on its id.
- `DELETE \id\`  - delete a specific exercise.

### Unresolved questions

Editing of an exercise is considered a larger problem, and is handled in #44 

### Definition of Done

When the above endpoints are available.

**Comment by KristianS93** [comment]
From Status: Esben urgently needs all exercises from a specific instructor, and deletion of an exercise. @JMyrtue, esben would like this to be a priority.

**Comment by JMyrtue** [comment]
`GET\` and `DELETE\id\` from the issue description is implemented in PR #69.

`GET\id\` depends on the functionality of #45, and thus will be implemented one this issue is resolved.
